sonar.projectKey=adaptia
sonar.projectName=Adaptia
sonar.projectVersion=1.0

sonar.sources=app,routes,config,database,resources
sonar.tests=tests

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/build/**

sonar.test.exclusions=vendor/**,node_modules/**

sonar.sourceEncoding=UTF-8